---
- name: Setup Jenkins and Docker
  hosts: all
  become: yes

  tasks:
    - name: Download Jenkins repository file
      get_url:
        url: https://pkg.jenkins.io/redhat-stable/jenkins.repo
        dest: /etc/yum.repos.d/jenkins.repo

    - name: Import Jenkins GPG key
      rpm_key:
        key: https://pkg.jenkins.io/redhat-stable/jenkins.io-2023.key
        state: present

    - name: Upgrade all packages
      yum:
        name: '*'
        state: latest

    - name: Install Jenkins dependencies
      yum:
        name:
          - fontconfig
          - java-17-openjdk
        state: present

    - name: Install Jenkins
      yum:
        name: jenkins
        state: present

    - name: Reload systemd daemon
      systemd:
        daemon_reload: yes

    - name: Enable Jenkins service
      systemd:
        name: jenkins
        enabled: yes

    - name: Start Jenkins service
      systemd:
        name: jenkins
        state: started

    - name: Install required packages for Docker
      yum:
        name:
          - yum-utils
          - device-mapper-persistent-data
          - lvm2
        state: present

    - name: Add Docker CE repository
      command: >
        yum-config-manager --add-repo
        https://download.docker.com/linux/centos/docker-ce.repo

    - name: Remove Podman Docker to avoid conflicts
      yum:
        name: podman-docker
        state: absent

    - name: Install Docker CE
      yum:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
        state: present

    - name: Ensure Docker group exists
      group:
        name: docker
        state: present

    - name: Ensure Docker service is started and enabled
      systemd:
        name: docker
        state: started
        enabled: yes
      ignore_errors: yes

    - name: Add current user to the docker group
      user:
        name: "{{ ansible_user_id }}"
        groups: docker
        append: yes

    - name: Verify Docker installation and print Docker version
      command: docker --version
      register: docker_version
      ignore_errors: yes

    - name: Print Docker version
      debug:
        msg: "{{ docker_version.stdout }}"
      when: docker_version is defined

    - name: Change permissions on /var/run/docker.sock
      file:
        path: /var/run/docker.sock
        mode: '0666'
