---
- name: Jenkins Slave Setup
  hosts: jenkins-slave
  become: true

  tasks:
  - name: Update Ubuntu Repo and Cache
    apt:
      update_cache: yes
      force_apt_get: yes
      cache_valid_time: 3600

  - name: Install Java
    apt:
      name: openjdk-17-jre
      state: present
      install_recommends: yes

  - name: Download Maven Package
    get_url:
      url: https://dlcdn.apache.org/maven/maven-3/3.9.6/binaries/apache-maven-3.9.6-bin.tar.gz
      dest: /opt

  - name: Extract Maven Package
    unarchive:
      src: /opt/apache-maven-3.9.6-bin.tar.gz
      dest: /opt
      remote_src: yes




  


