---
- name: Jenkins Slave Setup
  hosts: jenkins-slave
  become: true

  tasks:
  - name: Update Ubuntu Repo and Cache
    apt:
      update_cache: yes
      force_apt_get: yes
      cache_valid_time: 3600

  - name: Install Java
    apt:
      name: openjdk-17-jre
      state: present
      install_recommends: yes

  - name: Download Maven Package
    get_url:
      url: https://dlcdn.apache.org/maven/maven-3/3.9.6/binaries/apache-maven-3.9.6-bin.tar.gz
      dest: /opt

  - name: Extract Maven Package
    unarchive:
      src: /opt/apache-maven-3.9.6-bin.tar.gz
      dest: /opt
      remote_src: yes

  - name: Install Docker
    apt:
      name: docker.io
      state: present
      install_recommends: yes


  - name: Ensure Docker service is started and enabled
    service:
      name: docker
      state: started
      enabled: yes

  - name: Add current user to the docker group
    user:
      name: "{{ ansible_user_id }}"
      groups: docker
      append: yes

  - name: Verify Docker installation
    command: docker --version
    register: docker_version

  - name: Print Docker version
    debug:
      msg: "Docker version: {{ docker_version.stdout }}"
